In [1]:
import tensorflow as tf
print('TF version:', tf.__version__)

TF version: 2.17.1

In [2]:
tf.test.gpu_device_name()

''

In [3]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/Neha-Chiluka/tf/refs/heads/main/Chapter3-TensorFlowDevelopment/dataset/Summary_of_Weather.csv")

<ipython-input-3-84d990cdcd30>:2: DtypeWarning: Columns (7,8,18,25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("https://raw.githubusercontent.com/Neha-Chiluka/tf/refs/heads/main/Chapter3-TensorFlowDevelopment/dataset/Summary_of_Weather.csv")

In [4]:
df.head()

,STA,Date,Precip,WindGustSpd,MaxTemp,MinTemp,MeanTemp,Snowfall,PoorWeather,YR,...,FB,FTI,ITH,PGT,TSHDSBRSGF,SD3,RHX,RHN,RVG,WTE
0,10001,1942-7-1,1.016,NaN,25.555556,22.222222,23.888889,0.0,NaN,42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10001,1942-7-2,0,NaN,28.888889,21.666667,25.555556,0.0,NaN,42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10001,1942-7-3,2.54,NaN,26.111111,22.222222,24.444444,0.0,NaN,42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10001,1942-7-4,2.54,NaN,26.666667,22.222222,24.444444,0.0,NaN,42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10001,1942-7-5,0,NaN,26.666667,21.666667,24.444444,0.0,NaN,42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.drop("Date", axis=1, inplace=True)

In [6]:
df1 = df.iloc[:,2:6].dropna()

In [7]:
df1.head()

       WindGustSpd    MaxTemp    MinTemp   MeanTemp
51177       29.632  27.222222  22.222222  25.000000
51178       59.264  27.777778  22.777778  25.555556
51179       50.004  27.777778  22.777778  25.555556
51180       40.744  26.666667  23.888889  25.555556
51181       51.856  26.111111  23.888889  25.000000

In [8]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 532 entries, 51177 to 64046
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   WindGustSpd  532 non-null    float64
 1   MaxTemp      532 non-null    float64
 2   MinTemp      532 non-null    float64
 3   MeanTemp     532 non-null    float64
dtypes: float64(4)
memory usage: 20.8 KB

In [9]:
import numpy as np
df1 = np.asarray(df1).astype(np.float32)
random_tensor = tf.random.normal((df1.shape[1],1))

In [10]:
tf.matmul(df1, random_tensor)

<tf.Tensor: shape=(532, 1), dtype=float32, numpy=
array([[-74.004166],
       [-88.41042 ],
       [-84.34452 ],
       [-80.83097 ],
       [-85.00729 ],
       [-86.016045],
       [-83.5765  ],
       [-88.992584],
       [-89.03774 ],
       [-88.058815],
       [-85.12743 ],
       [-90.58914 ],
       [-92.04975 ],
       [-85.85029 ],
       [-91.17131 ],
       [-91.61752 ],
       [-87.87342 ],
       [-90.312965],
       [-93.520065],
       [-87.17066 ],
       [-84.52991 ],
       [-87.1352  ],
       [-90.61894 ],
       [-81.27718 ],
       [-91.93887 ],
       [-81.367516],
       [-83.530876],
       [-91.3567  ],
       [-87.59724 ],
       [-89.73034 ],
       [-96.035034],
       [-97.00381 ],
       [-91.155945],
       [-89.574745],
       [-86.31232 ],
       [-93.56523 ],
       [-87.87296 ],
       [-90.4331  ],
       [-89.26876 ],
       [-85.5443  ],
       [-83.85268 ],
       [-85.082275],
       [-92.9379  ],
       [-86.43245 ],
       [-89.49933 ],
       [-85.38825 ],
       [-88.335   ],
       [-81.71912 ],
       [-83.92765 ],
       [-87.1352  ],
       [-84.62069 ],
       [-86.43245 ],
       [-84.57552 ],
       [-86.247055],
       [-83.5765  ],
       [-85.50884 ],
       [-88.1794  ],
       [-87.6424  ],
       [-87.290794],
       [-88.59581 ],
       [-83.92765 ],
       [-82.301285],
       [-82.13553 ],
       [-81.25709 ],
       [-78.069626],
       [-79.695984],
       [-80.67493 ],
       [-81.44293 ],
       [-83.80706 ],
       [-81.488106],
       [-78.19021 ],
       [-81.82955 ],
       [-77.10651 ],
       [-86.20143 ],
       [-88.03872 ],
       [-87.01462 ],
       [-89.3889  ],
       [-82.44152 ],
       [-86.13618 ],
       [-87.22554 ],
       [-84.92622 ],
       [-85.433876],
       [-85.433426],
       [-81.44293 ],
       [-84.41948 ],
       [-82.180695],
       [-84.38922 ],
       [-82.883446],
       [-82.883446],
       [-81.25709 ],
       [-85.38825 ],
       [-82.83829 ],
       [-88.45513 ],
       [-84.52991 ],
       [-85.73985 ],
       [-83.88248 ],
       [-85.433426],
       [-83.88248 ],
       [-85.50884 ],
       [-82.94871 ],
       [-80.464005],
       [-82.883446],
       [-82.180695],
       [-83.69663 ],
       [-83.80706 ],
       [-83.29986 ],
       [-90.20208 ],
       [-86.949356],
       [-84.92622 ],
       [-84.113045],
       [-84.38968 ],
       [-86.156265],
       [-92.59646 ],
       [-83.761894],
       [-85.895454],
       [-84.50981 ],
       [-86.78361 ],
       [-85.112076],
       [-84.46465 ],
       [-90.47826 ],
       [-91.035355],
       [-91.38651 ],
       [-88.575714],
       [-85.97042 ],
       [-87.01462 ],
       [-88.640976],
       [-89.454155],
       [-91.58772 ],
       [-86.09101 ],
       [-83.45591 ],
       [-84.27879 ],
       [-80.12257 ],
       [-72.02621 ],
       [-84.15866 ],
       [-83.48571 ],
       [-80.74018 ],
       [-74.8169  ],
       [-81.71912 ],
       [-82.99388 ],
       [-86.29176 ],
       [-83.85268 ],
       [-80.71038 ],
       [-81.859344],
       [-78.14505 ],
       [-79.74116 ],
       [-84.92622 ],
       [-91.20111 ],
       [-82.44152 ],
       [-85.85999 ],
       [-80.70473 ],
       [-76.33284 ],
       [-84.46465 ],
       [-83.22489 ],
       [-87.59679 ],
       [-86.70863 ],
       [-85.343094],
       [-79.816574],
       [-81.36797 ],
       [-70.60106 ],
       [-80.67493 ],
       [-86.13618 ],
       [-86.29222 ],
       [-83.37529 ],
       [-83.06884 ],
       [-82.5621  ],
       [-84.29889 ],
       [-84.65004 ],
       [-83.06884 ],
       [-81.21192 ],
       [-82.83829 ],
       [-79.27957 ],
       [-83.69663 ],
       [-78.19021 ],
       [-76.67428 ],
       [-83.88203 ],
       [-85.925255],
       [-81.628334],
       [-85.628975],
       [-86.71834 ],
       [-85.67414 ],
       [-88.8817  ],
       [-81.136955],
       [-86.12081 ],
       [-79.11382 ],
       [-93.805954],
       [-89.76015 ],
       [-87.78263 ],
       [-86.442154],
       [-84.27879 ],
       [-82.67253 ],
       [-85.38825 ],
       [-82.09036 ],
       [-78.14459 ],
       [-84.665405],
       [-78.99368 ],
       [-89.71497 ],
       [-89.409   ],
       [-80.86032 ],
       [-84.06788 ],
       [-83.2547  ],
       [-84.113495],
       [-89.99116 ],
       [-83.88248 ],
       [-86.85902 ],
       [-90.739075],
       [-79.1888  ],
       [-82.65243 ],
       [-80.69502 ],
       [-83.57604 ],
       [-87.64195 ],
       [-85.20241 ],
       [-84.27879 ],
       [-83.48571 ],
       [-82.13553 ],
       [-84.27879 ],
       [-85.628975],
       [-85.628975],
       [-87.71692 ],
       [-87.10584 ],
       [-83.7716  ],
       [-80.90548 ],
       [-83.83686 ],
       [-84.60488 ],
       [-84.23363 ],
       [-88.92687 ],
       [-88.409966],
       [-86.01559 ],
       [-80.047134],
       [-81.6735  ],
       [-83.11446 ],
       [-83.69663 ],
       [-86.67317 ],
       [-87.180374],
       [-88.13379 ],
       [-79.15898 ],
       [-76.60902 ],
       [-79.46497 ],
       [-82.13553 ],
       [-77.76364 ],
       [-79.8972  ],
       [-78.74258 ],
       [-80.74018 ],
       [-78.069626],
       [-79.04856 ],
       [-81.71912 ],
       [-82.36655 ],
       [-82.76331 ],
       [-87.53152 ],
       [-82.60727 ],
       [-80.59995 ],
       [-88.640976],
       [-92.55129 ],
       [-86.69327 ],
       [-82.5621  ],
       [-75.584915],
       [-87.53152 ],
       [-84.92622 ],
       [-85.58381 ],
       [-86.181335],
       [-83.06884 ],
       [-84.92622 ],
       [-87.71738 ],
       [-80.55479 ],
       [-84.23363 ],
       [-84.113045],
       [-85.90516 ],
       [-93.07858 ],
       [-88.530556],
       [-81.859344],
       [-81.44293 ],
       [-84.23363 ],
       [-81.628334],
       [-86.045845],
       [-83.48571 ],
       [-81.71912 ],
       [-82.48668 ],
       [-85.58381 ],
       [-87.48636 ],
       [-94.333694],
       [-87.22554 ],
       [-81.76428 ],
       [-81.488106],
       [-81.628334],
       [-88.29954 ],
       [-88.409966],
       [-83.48571 ],
       [-83.29986 ],
       [-86.13618 ],
       [-81.56307 ],
       [-86.67317 ],
       [-80.665215],
       [-82.79311 ],
       [-84.50981 ],
       [-83.57604 ],
       [-84.27879 ],
       [-86.32202 ],
       [-83.69663 ],
       [-83.2547  ],
       [-77.272255],
       [-82.59757 ],
       [-88.761566],
       [-85.73985 ],
       [-88.91715 ],
       [-89.26876 ],
       [-87.40168 ],
       [-82.45734 ],
       [-86.828766],
       [-87.6722  ],
       [-87.56743 ],
       [-90.11175 ],
       [-85.343094],
       [-92.07955 ],
       [-84.03852 ],
       [-86.13618 ],
       [-83.34548 ],
       [-87.059784],
       [-52.295334],
       [-44.54493 ],
       [-44.991142],
       [-47.55127 ],
       [-46.818718],
       [-45.84994 ],
       [-44.379173],
       [-42.230255],
       [-51.70751 ],
       [-48.103638],
       [-49.057045],
       [-45.498337],
       [-48.670437],
       [-50.207394],
       [-52.274307],
       [-55.988617],
       [-52.445724],
       [-51.51241 ],
       [-48.364456],
       [-41.492493],
       [-56.12456 ],
       [-53.886234],
       [-55.512596],
       [-55.617367],
       [-55.87819 ],
       [-58.734142],
       [-55.376648],
       [-54.167152],
       [-50.89433 ],
       [-51.893356],
       [-51.61718 ],
       [-55.84838 ],
       [-50.452393],
       [-53.549072],
       [-51.938526],
       [-49.639214],
       [-60.496456],
       [-56.43055 ],
       [-57.354156],
       [-56.771988],
       [-60.300903],
       [-49.313133],
       [-52.536057],
       [-53.50483 ],
       [-49.820328],
       [-47.872616],
       [-51.155144],
       [-52.826675],
       [-58.122177],
       [-57.00301 ],
       [-53.4741  ],
       [-49.639214],
       [-50.52736 ],
       [-57.288895],
       [-59.913837],
       [-61.615166],
       [-57.62468 ],
       [-62.779945],
       [-58.563656],
       [-60.235634],
       [-56.214897],
       [-54.071632],
       [-46.940228],
       [-54.729218],
       [-52.400105],
       [-63.794342],
       [-56.892128],
       [-55.49678 ],
       [-57.705307],
       [-59.773605],
       [-55.542397],
       [-57.259094],
       [-56.70673 ],
       [-62.047394],
       [-57.78073 ],
       [-57.59488 ],
       [-55.893547],
       [-58.960423],
       [-57.981483],
       [-59.913837],
       [-56.094307],
       [-56.185093],
       [-55.727795],
       [-52.139282],
       [-49.77516 ],
       [-52.123924],
       [-51.737312],
       [-45.09729 ],
       [-49.00715 ],
       [-51.999054],
       [-53.027885],
       [-80.04759 ],
       [-73.46717 ],
       [-69.772514],
       [-76.352936],
       [-77.56288 ],
       [-74.681404],
       [-79.234406],
       [-73.05504 ],
       [-70.570335],
       [-73.03494 ],
       [-75.153145],
       [-79.58556 ],
       [-76.47352 ],
       [-72.19669 ],
       [-71.04207 ],
       [-70.570335],
       [-78.05471 ],
       [-79.695984],
       [-73.451805],
       [-75.93652 ],
       [-83.71673 ],
       [-79.003395],
       [-76.9351  ],
       [-78.45103 ],
       [-74.87696 ],
       [-75.84573 ],
       [-73.08485 ],
       [-73.898026],
       [-72.547844],
       [-76.7795  ],
       [-84.18847 ],
       [-80.373665],
       [-81.046165],
       [-82.83829 ],
       [-82.13553 ],
       [-75.705505],
       [-73.86822 ],
       [-72.47288 ],
       [-69.78696 ],
       [-70.75053 ],
       [-68.40605 ],
       [-70.84559 ],
       [-71.39796 ],
       [-69.95744 ],
       [-74.38986 ],
       [-71.09197 ],
       [-71.39796 ],
       [-73.45089 ],
       [-73.958084],
       [-74.94222 ],
       [-76.56858 ],
       [-81.26182 ],
       [-79.89627 ],
       [-77.04032 ],
       [-72.27166 ],
       [-73.66701 ],
       [-72.04065 ],
       [-81.38196 ],
       [-88.99213 ],
       [-88.48493 ],
       [-84.18847 ],
       [-81.56307 ],
       [-80.2427  ],
       [-81.47229 ],
       [-80.076935],
       [-78.591255],
       [-82.657166],
       [-80.44864 ],
       [-80.61439 ],
       [-83.95745 ],
       [-87.671745],
       [-87.02433 ],
       [-84.53961 ],
       [-77.5019  ],
       [-75.062355],
       [-76.025925],
       [-80.01641 ],
       [-77.08549 ],
       [-76.68872 ],
       [-77.5019  ],
       [-78.78682 ],
       [-80.68936 ],
       [-79.36898 ],
       [-79.87618 ],
       [-80.48815 ],
       [-79.20323 ],
       [-80.1668  ],
       [-81.36659 ],
       [-79.89062 ],
       [-80.613014],
       [-85.36724 ],
       [-84.524254],
       [-85.7692  ],
       [-83.45025 ],
       [-85.980125],
       [-83.911835],
       [-84.80043 ],
       [-83.8215  ],
       [-85.18139 ],
       [-83.89647 ],
       [-80.45835 ],
       [-80.22733 ],
       [-85.427765],
       [-87.591125],
       [-87.86731 ],
       [-90.16617 ],
       [-86.16552 ],
       [-87.239525],
       [-90.1508  ],
       [-86.039734],
       [-83.389275],
       [-83.00266 ],
       [-85.351425],
       [-82.4205  ],
       [-81.30134 ],
       [-81.57752 ],
       [-79.67497 ],
       [-88.14211 ],
       [-86.30055 ],
       [-94.00106 ],
       [-91.97793 ],
       [-90.77814 ],
       [-84.00261 ],
       [-84.614586],
       [-86.6219  ]], dtype=float32)>