In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
data_url = "https://raw.githubusercontent.com/fenago/tf/main/Chapter5-Classification_Models/datasets/ion.csv"

data = pd.read_csv(data_url)
data.pop('Unnamed: 0')
data.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V26,V27,V28,V29,V30,V31,V32,V33,V34,Class
0,1,0,0.99539,-0.05889,0.85243,0.02306,0.83398,-0.37708,1.00000,0.03760,...,-0.51171,0.41078,-0.46168,0.21266,-0.34090,0.42267,-0.54487,0.18641,-0.45300,good
1,1,0,1.00000,-0.18829,0.93035,-0.36156,-0.10868,-0.93597,1.00000,-0.04549,...,-0.26569,-0.20468,-0.18401,-0.19040,-0.11593,-0.16626,-0.06288,-0.13738,-0.02447,bad
2,1,0,1.00000,-0.03365,1.00000,0.00485,1.00000,-0.12062,0.88965,0.01198,...,-0.40220,0.58984,-0.22145,0.43100,-0.17365,0.60436,-0.24180,0.56045,-0.38238,good
3,1,0,1.00000,-0.45161,1.00000,1.00000,0.71216,-1.00000,0.00000,0.00000,...,0.90695,0.51613,1.00000,1.00000,-0.20099,0.25682,1.00000,-0.32382,1.00000,bad
4,1,0,1.00000,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,-0.16399,...,-0.65158,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697,good

In [3]:
reduce_map = {"Class": {"good":1, "bad":0} }
data.replace(reduce_map, inplace=True)

<ipython-input-3-79ad1e51b63a>:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.replace(reduce_map, inplace=True)

In [4]:
data.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V26,V27,V28,V29,V30,V31,V32,V33,V34,Class
0,1,0,0.99539,-0.05889,0.85243,0.02306,0.83398,-0.37708,1.00000,0.03760,...,-0.51171,0.41078,-0.46168,0.21266,-0.34090,0.42267,-0.54487,0.18641,-0.45300,1
1,1,0,1.00000,-0.18829,0.93035,-0.36156,-0.10868,-0.93597,1.00000,-0.04549,...,-0.26569,-0.20468,-0.18401,-0.19040,-0.11593,-0.16626,-0.06288,-0.13738,-0.02447,0
2,1,0,1.00000,-0.03365,1.00000,0.00485,1.00000,-0.12062,0.88965,0.01198,...,-0.40220,0.58984,-0.22145,0.43100,-0.17365,0.60436,-0.24180,0.56045,-0.38238,1
3,1,0,1.00000,-0.45161,1.00000,1.00000,0.71216,-1.00000,0.00000,0.00000,...,0.90695,0.51613,1.00000,1.00000,-0.20099,0.25682,1.00000,-0.32382,1.00000,0
4,1,0,1.00000,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,-0.16399,...,-0.65158,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697,1

In [5]:
y = data.pop('Class')
X = data

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30,
                                                    random_state=42)

In [7]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(245, 34)
(106, 34)
(245,)
(106,)

In [8]:
X_train.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V25,V26,V27,V28,V29,V30,V31,V32,V33,V34
79,0,0,1.00000,1.00000,1.00000,-1.00000,1.00000,1.00000,-1.00000,1.00000,...,1.00000,-1.00000,1.00000,1.00000,1.00000,1.00000,1.00000,-1.00000,-1.00000,1.00000
116,1,0,1.00000,-0.14754,1.00000,0.04918,0.57377,-0.01639,0.65574,0.01639,...,0.31148,-0.34426,0.52385,-0.20325,0.32787,-0.03279,0.27869,-0.44262,0.49180,-0.06557
18,1,0,0.67065,0.02528,0.66626,0.05031,0.57197,0.18761,0.08776,0.34081,...,0.48838,0.23724,0.46167,0.24618,0.43433,0.25306,0.40663,0.25792,1.00000,0.33036
223,1,0,0.97467,0.13082,0.94120,0.20036,0.88783,0.32248,0.89009,0.32711,...,0.26832,0.76210,0.16813,0.78541,0.07497,0.80439,-0.02962,0.77702,-0.10289,0.74242
104,1,0,0.28409,-0.31818,0.00000,0.00000,0.68182,-1.00000,0.30682,0.95833,...,0.24242,0.17803,1.00000,-0.23864,0.06061,-0.48485,0.16288,-0.70076,0.00000,0.00000

In [9]:
X_test.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V25,V26,V27,V28,V29,V30,V31,V32,V33,V34
157,1,0,0.47090,0.22751,0.42328,0.33598,0.25661,0.47619,0.01852,0.49471,...,-0.23280,0.00265,0.03574,-0.31739,0.15873,-0.21693,0.24868,-0.24339,0.26720,0.04233
342,1,0,0.82254,-0.07572,0.80462,0.00231,0.87514,-0.01214,0.86821,-0.07514,...,0.74451,-0.02370,0.76717,-0.02731,0.74046,-0.07630,0.70058,-0.04220,0.78439,0.01214
316,1,0,0.89589,0.39286,0.66129,0.71804,0.29521,0.90824,-0.04787,0.94415,...,0.21581,-0.85703,0.53229,-0.68593,0.74846,-0.40656,0.83142,-0.07029,0.76862,0.27926
234,1,0,0.68729,1.00000,0.91973,-0.76087,0.81773,0.04348,0.76087,0.10702,...,1.00000,-0.53846,0.89262,0.22216,0.71070,0.53846,1.00000,-0.06522,0.56522,0.23913
155,1,0,0.72414,-0.01084,0.79704,0.01084,0.80000,0.00197,0.79015,0.01084,...,0.72611,-0.01478,0.78041,0.00612,0.74089,-0.05025,0.82956,0.02956,0.79015,0.00788

In [10]:
y_train.head()

79     0
116    0
18     1
223    1
104    0
Name: Class, dtype: int64

In [11]:
y_test.head()

157    1
342    1
316    1
234    0
155    1
Name: Class, dtype: int64

In [12]:
import tensorflow as tf

In [15]:
model = tf.keras.models.load_model("/content/Chapter5_lab_01_model.h5")

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [16]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 512)                 │          17,920 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 512)                 │         262,656 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 128)                 │          65,664 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 128)                 │          16,512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 1)                   │             129 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 362,883 (1.38 MB)

 Trainable params: 362,881 (1.38 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2 (12.00 B)

In [17]:
preds_proba = model.predict(X_test)
preds_proba[:5]

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step

array([[0.97446287],
       [0.9881207 ],
       [0.9990501 ],
       [0.59485704],
       [0.98604   ]], dtype=float32)

In [18]:
preds = preds_proba >= 0.5
preds[:5]

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True]])

In [19]:
from tensorflow.keras.metrics import Accuracy, Precision, Recall

In [20]:
acc = Accuracy()
prec = Precision()
rec = Recall()

In [21]:
acc.update_state(preds, y_test)
acc_results = acc.result().numpy()
acc_results

0.9716981

In [22]:
prec.update_state(preds, y_test)
prec_results = prec.result().numpy()
prec_results

1.0

In [23]:
rec.update_state(preds, y_test)
rec_results = rec.result().numpy()
rec_results

0.95714283

In [24]:
f1 = 2*(prec_results * rec_results) / (prec_results + rec_results)
f1

0.9781021755539021