In [1]:
import pandas as pd

In [2]:
data_url = "https://raw.githubusercontent.com/fenago/tf/main/Chapter6-Regularization_and_Hyperparameter_Tuning/dataset/shuttle.trn"

data = pd.read_table(data_url, header=None, sep=' ')
data.head()

    0   1   2  3   4   5   6   7   8  9
0  50  21  77  0  28   0  27  48  22  2
1  55   0  92  0   0  26  36  92  56  4
2  53   0  82  0  52  -5  29  30   2  1
3  37   0  76  0  28  18  40  48   8  1
4  37   0  79  0  34 -26  43  46   2  1

In [3]:
data.isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
dtype: int64

In [4]:
y = data.pop(9)
X = data.copy()

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, stratify=y)

In [7]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

In [8]:
tf.random.set_seed(8)

In [9]:
model = tf.keras.Sequential()

In [10]:
fc1 = Dense(512, input_shape=(9,), activation='relu')

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [11]:
fc2 = Dense(512, activation='relu')
fc3 = Dense(128, activation='relu')
fc4 = Dense(128, activation='relu')

In [12]:
fc5 = Dense(8, activation='softmax')

In [13]:
model.add(fc1)
model.add(fc2)
model.add(fc3)
model.add(fc4)
model.add(fc5)

In [14]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 512)                 │           5,120 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 512)                 │         262,656 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 128)                 │          65,664 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 128)                 │          16,512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 8)                   │           1,032 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 350,984 (1.34 MB)

 Trainable params: 350,984 (1.34 MB)

 Non-trainable params: 0 (0.00 B)

In [15]:
loss = tf.keras.losses.SparseCategoricalCrossentropy()

In [16]:
optimizer = tf.keras.optimizers.Adam(0.001)

In [17]:
model.compile(optimizer=optimizer, loss=loss, \
                  metrics=['accuracy'])

In [18]:
model.fit(X_train, y_train, epochs=5, validation_split=0.2)

Epoch 1/5
762/762 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.9484 - loss: 0.5247 - val_accuracy: 0.9941 - val_loss: 0.0948
Epoch 2/5
762/762 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.9904 - loss: 0.1489 - val_accuracy: 0.9980 - val_loss: 0.0398
Epoch 3/5
762/762 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9936 - loss: 0.0879 - val_accuracy: 0.9856 - val_loss: 0.0875
Epoch 4/5
762/762 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9937 - loss: 0.0595 - val_accuracy: 0.9939 - val_loss: 0.0320
Epoch 5/5
762/762 ━━━━━━━━━━━━━━━━━━━━ 12s 11ms/step - accuracy: 0.9955 - loss: 0.0513 - val_accuracy: 0.9975 - val_loss: 0.0321

In [20]:
reg_fc1 = Dense(512, input_shape=(9,), activation='relu',
                    kernel_regularizer=tf.keras.regularizers.l2(l2=0.1))
reg_fc2 = Dense(512, activation='relu',
                    kernel_regularizer=tf.keras.regularizers.l2(l2=0.1))
reg_fc3 = Dense(128, activation='relu',
                    kernel_regularizer=tf.keras.regularizers.l2(l2=0.1))
reg_fc4 = Dense(128, activation='relu',
                    kernel_regularizer=tf.keras.regularizers.l2(l2=0.1))
reg_fc5 = Dense(8, activation='softmax')

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [21]:

model2 = tf.keras.Sequential()
model2.add(reg_fc1)
model2.add(reg_fc2)
model2.add(reg_fc3)
model2.add(reg_fc4)
model2.add(reg_fc5)

In [22]:
model2.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_5 (Dense)                      │ (None, 512)                 │           5,120 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_6 (Dense)                      │ (None, 512)                 │         262,656 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (None, 128)                 │          65,664 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_8 (Dense)                      │ (None, 128)                 │          16,512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_9 (Dense)                      │ (None, 8)                   │           1,032 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 350,984 (1.34 MB)

 Trainable params: 350,984 (1.34 MB)

 Non-trainable params: 0 (0.00 B)

In [23]:
model2.compile(optimizer=optimizer, loss=loss, \
                   metrics=['accuracy'])

In [25]:
# Create a new optimizer instance for model2
optimizer2 = tf.keras.optimizers.Adam(0.001) # use a new variable so it is clear which one we're using.
model2.compile(optimizer=optimizer2, loss=loss, metrics=['accuracy'])
model2.fit(X_train, y_train, epochs=5, validation_split=0.2)

Epoch 1/5
762/762 ━━━━━━━━━━━━━━━━━━━━ 11s 13ms/step - accuracy: 0.8925 - loss: 20.0282 - val_accuracy: 0.9327 - val_loss: 0.6334
Epoch 2/5
762/762 ━━━━━━━━━━━━━━━━━━━━ 9s 12ms/step - accuracy: 0.9311 - loss: 0.6423 - val_accuracy: 0.9593 - val_loss: 0.3494
Epoch 3/5
762/762 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.9715 - loss: 0.3341 - val_accuracy: 0.9639 - val_loss: 0.2695
Epoch 4/5
762/762 ━━━━━━━━━━━━━━━━━━━━ 10s 13ms/step - accuracy: 0.9772 - loss: 0.2686 - val_accuracy: 0.9668 - val_loss: 0.2433
Epoch 5/5
762/762 ━━━━━━━━━━━━━━━━━━━━ 9s 12ms/step - accuracy: 0.9763 - loss: 0.2552 - val_accuracy: 0.9603 - val_loss: 0.2507